# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160509_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
