# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('duration', models.CharField(blank=True, max_length=40, null=True)),
                ('genre', models.CharField(blank=True, choices=[('Musical', 'Musical'), ('Opera', 'Opera'), ('Play', 'Play'), ('Ballet', 'Ballet'), ('Classical', 'Classical'), ('Comedy', 'Comedy'), ('Opera', 'Opera')], max_length=20, null=True)),
                ('crew_size', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('family_friendly', models.NullBooleanField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_venue', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
